### ISSUE TITLE
Update for newest Julia / CxxWrap

### ISSUE THREAD

**Issue by Psirus** [barche/EigenCpp.jl#1]
I've tried to use your Eigen wrapper, but got stuck (still new to Julia). First, the name of the CxxWrap header has changed, as well as the namespace (they are now called `jlcxx.hpp` and `jlcxx`, respectively). After that, it compiles, but when I run it in Julia it gives the following error:
~~~
ERROR: LoadError: ArgumentError: method definition for convert at :0 has free type 
variables
~~~
Any hints on what to do?

**Comment by barche** [comment]
If you want to update this, I'd propose you submit a PR with the changes as you have them now, then I can take a look at what causes this. There were a lot of changes in the handling of templates since I wrote this, so that's probably the cause.

Note that this package is really just an experiment that I did to test wrapping a non-trivial library, so it doesn't have any useful functionality and I don't plan to develop it further.

**Comment by Psirus** [comment]
It's unfortunate (for me) that you don't want to develop this further, but totally understandable. But at least it will be useful in getting an idea how this wrapping works, and maybe I can then extend this on my own. Thanks

**Comment by gzhang8** [comment]
@barche Great work. This is a very useful repo. When interacting with c++ code, it will be very handy if there are few working examples for Eigen. Like the pybind11 has native support for Eigen. Please consider adding this example to the CxxWrap library.


BTW, I get this error when I call Pkg.build("EigenCpp")

CMake Warning at CMakeLists.txt:10 (find_package):
  By not providing "FindCxxWrap.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "CxxWrap", but
  CMake did not find one.

  Could not find a package configuration file provided by "CxxWrap" with any
  of the following names:

    CxxWrapConfig.cmake
    cxxwrap-config.cmake

**Comment by barche** [comment]
@Psirus Thanks for the PR, the merged version with my changes should work
@gzhang8 That error is due to a change in CxxWrap in the location of the CMake config file, the changes just pushed should also fix it if you are on CxxWrap master.

**Comment by Psirus** [comment]
Thank you very much.
